# Generated by Django 2.2.2 on 2019-06-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Top_headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.TextField()),
                ('auther', models.TextField()),
                ('title', models.TextField(unique=True)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('urlToImage', models.TextField()),
                ('publishedAt', models.TextField()),
                ('content', models.TextField()),
                ('category', models.TextField()),
                ('initial_score', models.TextField()),
                ('upload_date', models.TextField()),
            ],
        ),
    ]
