# Generated by Django 2.2.2 on 2019-06-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_headline',
            name='auther',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='top_headline',
            name='category',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='top_headline',
            name='initial_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='top_headline',
            name='source_name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='top_headline',
            name='upload_date',
            field=models.CharField(max_length=1024),
        ),
    ]
