# Generated by Django 2.2.2 on 2019-06-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_newssource'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_headline',
            name='imageStatusCode',
            field=models.PositiveSmallIntegerField(default=200),
        ),
    ]
