# Generated by Django 2.2.2 on 2019-06-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_top_headline_imagestatuscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='top_headline',
            name='imageStatusCode',
        ),
    ]
